// Generated by typings
// Source: https://raw.githubusercontent.com/rinzeb/DefinitelyTyped/681d6bb905ff2aa90f8373904697ac35e15131e1/webshot/webshot.d.ts
interface webshotstatic {
    (content: any, filename: string, options: any, callback: Function): void;
}

declare module "webshot" {
    export = webshot;
}
declare var webshot: webshotstatic;
