// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/angularLocalStorage/angularLocalStorage.d.ts
declare namespace angular.localStorage {
  interface ILocalStorageService {
    set(key: string, value: any): any;
    get(key: string): any;
    remove(key: string): boolean;
    clearAll(): void;

    bind($scope: ng.IScope, key: string, opts?: {
      defaultValue?: any;
      storeName?: string;
    }): any;
    unbind($scope: ng.IScope, key: string, storeName?: string): void;
  }
}
