// Generated by typings
// Source: https://raw.githubusercontent.com/rinzeb/DefinitelyTyped/09e844c1ef5a2b4b5bda6c672453cc7f1fdfe0c6/xbbcode/xbbcode.d.ts
declare module XBBCODE {
    export interface IConfig {
        text                  : string;
        removeMisalignedTags? : boolean;
        addInLineBreaks?      : boolean;
    }

    export interface IBBCodeResult {
        html        : string;
        error       : boolean; 
        errorQueue? : string[];
    }

    export function process(config: IConfig): IBBCodeResult;
}
