// Generated by typings
// Source: https://raw.githubusercontent.com/rinzeb/DefinitelyTyped/09e844c1ef5a2b4b5bda6c672453cc7f1fdfe0c6/mqtt-router/mqtt-router.d.ts
declare module "mqtt-router" {
    var mqttrouter: mqttrouter.MqttClientWrapper;

    export = mqttrouter;

    module mqttrouter {
        interface MqttClientWrapper {
            wrap(mqttClient: any): MqttRouter;
        }

        interface MqttRouter {
            subscribe(topic: string, callback: (topic: string, message: any, params?: any) => void);
        }
    }
}
//declare var mqttrouter: "mqtt-router".MqttClientWrapper;


// interface MqttClientWrapper {
//     wrap(mqttClient: any): MqttRouter;
// }
//
// interface MqttRouter {
//     subscribe(topic: string, callback: (topic: string, message: any, params?: any) => {});
// }
//
// declare var mqttrouter: MqttClientWrapper;
//
// declare module "mqtt-router" {
//     export = mqttrouter;
// }
